using System.Collections.Generic;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppForSEII2526.API.Models
{
    public class Rental
    {
        public Rental()
        {
        }

        public Rental(string name, string surname, ApplicationUser applicationUser, string deliveryAddress, DateTime rentalDate, PaymentMethodTypes paymentMethod, DateTime rentalDateFrom, DateTime rentalDateTo, IList<RentDevice> rentalItems)
        {
            TotalPrice = rentalItems.Sum(ri => ri.Price * (rentalDateTo - rentalDateFrom).Days);

            //autogenerated
            RentalDateFrom = rentalDateFrom;
            RentalDateTo = rentalDateTo;
            RentalDate = rentalDate;
            DeliveryAddress = deliveryAddress;
            Name = name;
            Surname = surname;
            ApplicationUser = applicationUser;
            RentalItems = rentalItems;
            PaymentMethod = paymentMethod;
            ApplicationUserId = applicationUser.Id;
        }
        public int Id { get; set; }

        public double TotalPrice { get; set; }

        public DateTime RentalDate { get; set; }

        public DateTime RentalDateFrom { get; set; }
        public DateTime RentalDateTo { get; set; }


        [DataType(System.ComponentModel.DataAnnotations.DataType.MultilineText)]
        [Display(Name = "Delivery Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please, set your address for delivery")]
        public string DeliveryAddress { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please, set your name for rental")]
        public string Name { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please, set your surname for rental")]
        public string Surname { get; set; }
        [Display(Name = "Payment Method")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please, set your payment method for rental")]
        public PaymentMethodTypes PaymentMethod { get; set; }

        public IList<RentDevice> RentalItems { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
        
        [Required]
        public string ApplicationUserId { get; set; }

        public override bool Equals(object? obj)
        {
            return obj is Rental rental &&
                   Id == rental.Id &&
                   TotalPrice == rental.TotalPrice &&
                   RentalDateFrom.Subtract(rental.RentalDateFrom) < TimeSpan.FromMinutes(2) &&
                   RentalDateFrom == rental.RentalDateFrom &&
                   RentalDateTo == rental.RentalDateTo &&
                   DeliveryAddress == rental.DeliveryAddress &&
                   Name == rental.Name &&
                   Surname == rental.Surname &&
                   RentalItems.SequenceEqual(rental.RentalItems);
        }
        public override int GetHashCode()
        {
            return HashCode.Combine(Id,Name );
        }
    }
    public enum PaymentMethodTypes
    {
        CreditCard,
        PayPal,
        Cash
    }

}
